/// Flutter icons Findlove
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Findlove
///      fonts:
///       - asset: fonts/Findlove.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Findlove {
  Findlove._();

  static const _kFontFam = 'Findlove';
  static const String? _kFontPkg = null;

  static const IconData heart_badoo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personality_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_cupidon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData translate = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cards = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
